import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: ["typescript", "jsx-a11y", "react", "import"],
  jsPlugins: [
    {
      name: "stylistic",
      specifier: "@stylistic/eslint-plugin",
    },
    {
      name: "anti-slop",
      specifier: "./tools/oxlint/anti-slop/index.ts",
    },
  ],
  categories: {
    correctness: "error",
    suspicious: "error",
  },
  options: {
    typeAware: true,
  },
  env: {
    builtin: true,
    browser: true,
    node: true,
  },
  ignorePatterns: [
    "**/*.js",
    "dist/**",
    "coverage/**",
    "src/routeTree.gen.ts",
    "tools/oxlint/anti-slop/**",
    ".agent/**",
    ".agents/**",
    ".claude/**",
    ".codex/**",
    ".continue/**",
    ".cursor/**",
    ".gemini/**",
    ".opencode/**",
    ".pi/**",
    ".roo/**",
    ".windsurf/**",
  ],
  rules: {
    "no-case-declarations": "error",
    "no-empty": [
      "error",
      {
        allowEmptyCatch: true,
      },
    ],
    "no-fallthrough": "error",
    "no-prototype-builtins": "error",
    "no-unexpected-multiline": "error",
    "no-array-constructor": "error",
    "typescript/ban-ts-comment": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-assignment": "error",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-enum-comparison": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/only-throw-error": "error",
    "typescript/prefer-promise-reject-errors": "error",
    "typescript/require-await": "error",
    "typescript/restrict-plus-operands": "error",
    "typescript/no-confusing-non-null-assertion": "error",
    "typescript/prefer-nullish-coalescing": "error",
    "react/react-in-jsx-scope": "off",
    "import/no-unassigned-import": [
      "error",
      {
        allow: ["**/*.css", "**/i18n/config", "@testing-library/**"],
      },
    ],
    "typescript/consistent-return": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "anti-slop/no-chained-type-assertions": "warn",
    "anti-slop/no-conditional-empty-object-spread": "warn",
    "anti-slop/no-known-value-widening": "warn",
    "anti-slop/no-module-mocking": "warn",
    "anti-slop/no-object-parameters": "warn",
    "anti-slop/no-reflect-apply": "warn",
    "anti-slop/no-reflect-get": "warn",
    "anti-slop/no-runtime-typeof": "warn",
    "anti-slop/no-shape-in-symbol-names": "warn",
    "anti-slop/no-unknown-parameters": "warn",
    "anti-slop/no-unknown-returns": "warn",
    "anti-slop/no-unknown-type-aliases": "warn",
    "anti-slop/no-unsafe-dictionary-type": "warn",
    "anti-slop/no-widen-then-assert": "warn",
    "anti-slop/require-safety-comment-for-type-assertion": "warn",
  },
  overrides: [
    {
      files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
      rules: {
        "constructor-super": "off",
        "getter-return": "off",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-dupe-class-members": "off",
        "no-dupe-keys": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls": "off",
        "no-redeclare": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-unreachable": "off",
        "no-unsafe-negation": "off",
        "no-var": "error",
        "no-with": "off",
        "prefer-const": "error",
        "jsx-a11y/control-has-associated-label": "off",
        "jsx-a11y/prefer-tag-over-role": "off",
        "jsx-a11y/interactive-supports-focus": [
          "error",
          {
            tabbable: [
              "button",
              "checkbox",
              "link",
              "searchbox",
              "spinbutton",
              "switch",
              "textbox",
            ],
          },
        ],
        "jsx-a11y/no-interactive-element-to-noninteractive-role": [
          "error",
          {
            tr: ["none", "presentation"],
            canvas: ["img"],
          },
        ],
        "jsx-a11y/no-noninteractive-element-interactions": [
          "error",
          {
            handlers: [
              "onClick",
              "onError",
              "onLoad",
              "onMouseDown",
              "onMouseUp",
              "onKeyPress",
              "onKeyDown",
              "onKeyUp",
            ],
            alert: ["onKeyUp", "onKeyDown", "onKeyPress"],
            body: ["onError", "onLoad"],
            dialog: ["onKeyUp", "onKeyDown", "onKeyPress"],
            iframe: ["onError", "onLoad"],
            img: ["onError", "onLoad"],
          },
        ],
        "jsx-a11y/no-noninteractive-element-to-interactive-role": [
          "error",
          {
            ul: ["listbox", "menu", "menubar", "radiogroup", "tablist", "tree", "treegrid"],
            ol: ["listbox", "menu", "menubar", "radiogroup", "tablist", "tree", "treegrid"],
            li: [
              "menuitem",
              "menuitemradio",
              "menuitemcheckbox",
              "option",
              "row",
              "tab",
              "treeitem",
            ],
            table: ["grid"],
            td: ["gridcell"],
            fieldset: ["radiogroup", "presentation"],
          },
        ],
        "jsx-a11y/no-noninteractive-tabindex": [
          "error",
          {
            tags: [],
            roles: ["tabpanel"],
            allowExpressionValues: true,
          },
        ],
        "jsx-a11y/no-static-element-interactions": [
          "error",
          {
            allowExpressionValues: true,
            handlers: ["onClick", "onMouseDown", "onMouseUp", "onKeyPress", "onKeyDown", "onKeyUp"],
          },
        ],
        "import/first": "warn",
        "stylistic/padding-line-between-statements": [
          "warn",
          {
            blankLine: "always",
            prev: "*",
            next: "return",
          },
        ],
        "react/rules-of-hooks": "error",
        "react/unsupported-syntax": "warn",
        "typescript/consistent-type-definitions": ["error", "interface"],
        "typescript/no-misused-promises": [
          "error",
          {
            checksVoidReturn: {
              attributes: false,
            },
          },
        ],
        "react/exhaustive-deps": "warn",
        "react/incompatible-library": "warn",
      },
    },
    {
      files: ["**/*.test.{ts,tsx}", "src/test/**/*.ts", "tests/**/*.ts"],
      rules: {
        "require-yield": "off",
        "typescript/require-await": "off",
        "typescript/no-unsafe-assignment": "off",
        "typescript/no-unsafe-member-access": "off",
      },
    },
  ],
  globals: {
    AsyncDisposableStack: "readonly",
    DisposableStack: "readonly",
    SuppressedError: "readonly",
  },
});
