export const apiPaths = {
  session: "/api/session",
  cards: "/api/cards",
  collections: "/api/collections",
  topics: "/api/topics",
  reviews: "/api/reviews",
  stats: "/api/stats",
  card: (cardId: string) => `/api/cards/${cardId}`,
  collection: (collectionId: string) => `/api/collections/${collectionId}`,
  topic: (topicId: string) => `/api/topics/${topicId}`,
  tutorReplies: "/api/tutor-replies",
  audio: (audioId: string) => `/api/audio/${audioId}`,
  stageAudio: "/api/audio",
  pronunciations: "/api/pronunciations",
} as const;
