import { z } from "zod";

export const problemTypes = {
  cardFrontConflict: "/problems/card-front-conflict",
  cardNotFound: "/problems/card-not-found",
  collectionNameConflict: "/problems/collection-name-conflict",
  collectionNotEmpty: "/problems/collection-not-empty",
  collectionNotFound: "/problems/collection-not-found",
  deviceClockAhead: "/problems/device-clock-ahead",
  invalidOrigin: "/problems/invalid-origin",
  invalidAudio: "/problems/invalid-audio",
  invalidAudioRange: "/problems/invalid-audio-range",
  audioNotFound: "/problems/audio-not-found",
  audioNotOwned: "/problems/audio-not-owned",
  audioUploadRateLimit: "/problems/audio-upload-rate-limit",
  audioPlaybackRateLimit: "/problems/audio-playback-rate-limit",
  invalidRequest: "/problems/invalid-request",
  lastCollection: "/problems/last-collection",
  topicNameConflict: "/problems/topic-name-conflict",
  topicNotFound: "/problems/topic-not-found",
  loginRateLimit: "/problems/login-rate-limit",
  pronunciationFailed: "/problems/pronunciation-failed",
  requestTooLarge: "/problems/request-too-large",
  reviewReplayConflict: "/problems/review-replay-conflict",
  reviewTooOld: "/problems/review-too-old",
  tutorDailyLimit: "/problems/tutor-daily-limit",
  tutorFailed: "/problems/tutor-failed",
  tutorAudioUnsupported: "/problems/tutor-audio-unsupported",
  tutorSessionLimit: "/problems/tutor-session-limit",
  unauthenticated: "/problems/unauthenticated",
  unexpected: "/problems/unexpected",
  unreadableRequest: "/problems/unreadable-request",
  unsupportedContentType: "/problems/unsupported-content-type",
  wrongPassword: "/problems/wrong-password",
} as const;

export const problemSchema = z.object({
  type: z.string().startsWith("/problems/"),
  title: z.string().min(1),
  status: z.number().int().min(400).max(599),
  instance: z.string().startsWith("urn:uuid:"),
  detail: z.string().optional(),
  errors: z.array(z.object({ pointer: z.string(), code: z.string() })).optional(),
});
export type Problem = z.infer<typeof problemSchema>;
