import { readFile } from "node:fs/promises";

interface PackageEntry {
  license?: string;
  licenses?: { type?: string }[];
}

interface PackageLock {
  packages: Record<string, PackageEntry>;
}

interface LicensePolicy {
  approved: string[];
  overrides?: Record<string, string>;
}

// SAFETY: package-lock.json is generated by npm and committed to this repository, so its shape is
// controlled here rather than supplied by a caller. A mismatch fails this dev-only script loudly.
const lock = JSON.parse(await readFile("package-lock.json", "utf8")) as PackageLock;
// SAFETY: license-policy.json is committed to this repository, so its shape is controlled here.
const policy = JSON.parse(await readFile("license-policy.json", "utf8")) as LicensePolicy;
const approved = new Set(policy.approved);
const failures: string[] = [];

for (const [path, entry] of Object.entries(lock.packages)) {
  if (!path.startsWith("node_modules/")) continue;
  const name = path.slice("node_modules/".length);
  let license = policy.overrides?.[name] ?? entry.license;

  if (!license) {
    // SAFETY: this reads only `license` and `licenses`, both optional in PackageEntry, so a
    // manifest missing them is handled by the fallback below rather than crashing.
    const manifest = JSON.parse(await readFile(`${path}/package.json`, "utf8")) as PackageEntry;
    license = manifest.license ?? manifest.licenses?.map((item) => item.type).join(" OR ");
  }
  if (!license || !approved.has(license)) failures.push(`${name}: ${license ?? "missing"}`);
}

if (failures.length > 0) {
  throw new Error(`Unapproved or unclear dependency licenses:\n${failures.join("\n")}`);
}

process.stdout.write(
  `All dependency licenses match the reviewed policy (${approved.size} forms).\n`,
);
