/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardsIndexRouteImport } from './routes/cards.index'
import { Route as ReviewSessionRouteImport } from './routes/review.session'
import { Route as CardsCollectionIdRouteImport } from './routes/cards.$collectionId'
import { Route as CardsCollectionIdCardIdRouteImport } from './routes/cards.$collectionId.$cardId'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CardsRoute,
} as any)
const ReviewSessionRoute = ReviewSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => ReviewRoute,
} as any)
const CardsCollectionIdRoute = CardsCollectionIdRouteImport.update({
  id: '/$collectionId',
  path: '/$collectionId',
  getParentRoute: () => CardsRoute,
} as any)
const CardsCollectionIdCardIdRoute = CardsCollectionIdCardIdRouteImport.update({
  id: '/$cardId',
  path: '/$cardId',
  getParentRoute: () => CardsCollectionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/review': typeof ReviewRouteWithChildren
  '/cards/$collectionId': typeof CardsCollectionIdRouteWithChildren
  '/review/session': typeof ReviewSessionRoute
  '/cards/': typeof CardsIndexRoute
  '/cards/$collectionId/$cardId': typeof CardsCollectionIdCardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/review': typeof ReviewRouteWithChildren
  '/cards/$collectionId': typeof CardsCollectionIdRouteWithChildren
  '/review/session': typeof ReviewSessionRoute
  '/cards': typeof CardsIndexRoute
  '/cards/$collectionId/$cardId': typeof CardsCollectionIdCardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/review': typeof ReviewRouteWithChildren
  '/cards/$collectionId': typeof CardsCollectionIdRouteWithChildren
  '/review/session': typeof ReviewSessionRoute
  '/cards/': typeof CardsIndexRoute
  '/cards/$collectionId/$cardId': typeof CardsCollectionIdCardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/login'
    | '/me'
    | '/review'
    | '/cards/$collectionId'
    | '/review/session'
    | '/cards/'
    | '/cards/$collectionId/$cardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/me'
    | '/review'
    | '/cards/$collectionId'
    | '/review/session'
    | '/cards'
    | '/cards/$collectionId/$cardId'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/login'
    | '/me'
    | '/review'
    | '/cards/$collectionId'
    | '/review/session'
    | '/cards/'
    | '/cards/$collectionId/$cardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  ReviewRoute: typeof ReviewRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/': {
      id: '/cards/'
      path: '/'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof CardsRoute
    }
    '/review/session': {
      id: '/review/session'
      path: '/session'
      fullPath: '/review/session'
      preLoaderRoute: typeof ReviewSessionRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/cards/$collectionId': {
      id: '/cards/$collectionId'
      path: '/$collectionId'
      fullPath: '/cards/$collectionId'
      preLoaderRoute: typeof CardsCollectionIdRouteImport
      parentRoute: typeof CardsRoute
    }
    '/cards/$collectionId/$cardId': {
      id: '/cards/$collectionId/$cardId'
      path: '/$cardId'
      fullPath: '/cards/$collectionId/$cardId'
      preLoaderRoute: typeof CardsCollectionIdCardIdRouteImport
      parentRoute: typeof CardsCollectionIdRoute
    }
  }
}

interface CardsCollectionIdRouteChildren {
  CardsCollectionIdCardIdRoute: typeof CardsCollectionIdCardIdRoute
}

const CardsCollectionIdRouteChildren: CardsCollectionIdRouteChildren = {
  CardsCollectionIdCardIdRoute: CardsCollectionIdCardIdRoute,
}

const CardsCollectionIdRouteWithChildren =
  CardsCollectionIdRoute._addFileChildren(CardsCollectionIdRouteChildren)

interface CardsRouteChildren {
  CardsCollectionIdRoute: typeof CardsCollectionIdRouteWithChildren
  CardsIndexRoute: typeof CardsIndexRoute
}

const CardsRouteChildren: CardsRouteChildren = {
  CardsCollectionIdRoute: CardsCollectionIdRouteWithChildren,
  CardsIndexRoute: CardsIndexRoute,
}

const CardsRouteWithChildren = CardsRoute._addFileChildren(CardsRouteChildren)

interface ReviewRouteChildren {
  ReviewSessionRoute: typeof ReviewSessionRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewSessionRoute: ReviewSessionRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRouteWithChildren,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  ReviewRoute: ReviewRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
